title: Pallabee Das # your name (or website title) here
logo: "/images/avatar-logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <center>Currently I am working on data science projects and aim to showcase my experience, knowledge and interests through my portfolio.<center>
  
  <center><a href="https://www.linkedin.com/in/pallabee-das-02610a23/">LinkedIn</a> | <a href="https://github.com/pallabee">GitHub</a><center>
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
